language: generic

branches:
  only:
    - master

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y luarocks
  - sudo luarocks install luacheck

script: luacheck --no-color ./mods
